apiVersion: v2
description: AWS EBS CSI driver ServiceMonitors
name: aws-ebs-csi-driver-servicemonitors
version: 0.2.0-dev
appVersion: 1.0.0
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  io.giantswarm.application.team: "phoenix"
home: https://github.com/giantswarm/aws-ebs-csi-driver-servicemonitors-app
keywords:
  - monitoring
restrictions:
  clusterSingleton: true
  fixedNamespace: kube-system
type: application
